export const AIRLINES = [
  { id: 'AA', name: 'American Airlines' },
  { id: 'AS', name: 'Alaska Airlines' },
  { id: 'B6', name: 'JetBlue Airways' },
  { id: 'DL', name: 'Delta Air Lines' },
  { id: 'EV', name: 'ExpressJet Airlines' },
  { id: 'F9', name: 'Frontier Airlines' },
  { id: 'HA', name: 'Hawaiian Airlines' },
  { id: 'MQ', name: 'Envoy Air' },
  { id: 'NK', name: 'Spirit Airlines' },
  { id: 'OO', name: 'SkyWest Airlines' },
  { id: 'UA', name: 'United Airlines' },
  { id: 'US', name: 'US Airways' },
  { id: 'VX', name: 'Virgin America' },
  { id: 'WN', name: 'Southwest Airlines' },
];

export const AIRPORTS = [
  { id: 'ATL', name: 'Hartsfield-Jackson Atlanta International' },
  { id: 'DFW', name: 'Dallas/Fort Worth International' },
  { id: 'DEN', name: 'Denver International' },
  { id: 'ORD', name: 'Chicago O\'Hare International' },
  { id: 'LAX', name: 'Los Angeles International' },
  { id: 'JFK', name: 'John F. Kennedy International' },
  { id: 'MCO', name: 'Orlando International' },
  { id: 'LAS', name: 'Harry Reid International' },
  { id: 'CLT', name: 'Charlotte Douglas International' },
  { id: 'MIA', name: 'Miami International' },
  { id: 'SEA', name: 'Seattle-Tacoma International' },
  { id: 'EWR', name: 'Newark Liberty International' },
  { id: 'SFO', name: 'San Francisco International' },
  { id: 'PHX', name: 'Phoenix Sky Harbor International' },
  { id: 'IAH', name: 'George Bush Intercontinental' },
  { id: 'BOS', name: 'Boston Logan International' },
  { id: 'FLL', name: 'Fort Lauderdale-Hollywood International' },
  { id: 'MSP', name: 'Minneapolis-St. Paul International' },
  { id: 'LGA', name: 'LaGuardia' },
  { id: 'DTW', name: 'Detroit Metropolitan' },
  { id: 'PHL', name: 'Philadelphia International' },
  { id: 'SLC', name: 'Salt Lake City International' },
  { id: 'BWI', name: 'Baltimore/Washington International' },
  { id: 'SAN', name: 'San Diego International' },
  { id: 'TPA', name: 'Tampa International' },
  { id: 'MDW', name: 'Chicago Midway International' },
  { id: 'IAD', name: 'Washington Dulles International' },
  { id: 'BNA', name: 'Nashville International' },
  { id: 'DAL', name: 'Dallas Love Field' },
  { id: 'DCA', name: 'Ronald Reagan Washington National' },
  { id: 'AUS', name: 'Austin-Bergstrom International' },
  { id: 'HNL', name: 'Daniel K. Inouye International' },
  { id: 'PDX', name: 'Portland International' },
  { id: 'MSY', name: 'Louis Armstrong New Orleans' },
  { id: 'STL', name: 'St. Louis Lambert International' },
  { id: 'RDU', name: 'Raleigh-Durham International' },
  { id: 'SJC', name: 'San Jose International' },
  { id: 'OAK', name: 'Oakland International' },
  { id: 'SMF', name: 'Sacramento International' },
  { id: 'SNA', name: 'John Wayne' },
  { id: 'MCI', name: 'Kansas City International' },
  { id: 'RSW', name: 'Southwest Florida International' },
  { id: 'CLE', name: 'Cleveland Hopkins International' },
  { id: 'IND', name: 'Indianapolis International' },
  { id: 'PIT', name: 'Pittsburgh International' },
  { id: 'SAT', name: 'San Antonio International' },
  { id: 'JAX', name: 'Jacksonville International' },
  { id: 'CMH', name: 'John Glenn Columbus International' },
  { id: 'CVG', name: 'Cincinnati/Northern Kentucky' },
  { id: 'MKE', name: 'General Mitchell International' }
];

export const getAirportName = (id: string) => AIRPORTS.find(a => a.id === id)?.name || id;
export const getAirlineName = (id: string) => AIRLINES.find(a => a.id === id)?.name || id;
